app: interblock
name: lambda-stream-processor
component: aws-lambda
inputs:
  runtime: nodejs12.x
  src: ./dist
  handler: streamProcessor.handler
  memory: 3008
  timeout: 30
  # triggers:
  #   - ${sqsSafety.arn}
  # tracing: true
  region: 'eu-central-1'
  env:
    DEBUG: '*'
    DEBUG_COLORS: '0'
    DEBUG_HIDE_DATE: '1'
  layers:
    - ${output:${stage}:${app}:lambda-layer.arnVersion}
  roleName: lambda-stream-processor-dev-qhlamh-lambda-role
