name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
      - run: npm config set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN}
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - run: yarn
      - run: yarn run release --no-tests --no-2fa patch


