name: Minimal setup
on:
  push:
    branches:
      - master
permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Run benchmark
        working-directory: pkg/interblock
        run: yarn bench | tee output.txt
      - name: Store benchmark result
        working-directory: pkg/interblock
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: 'benchmarkjs'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
