name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "interbot"
      - run: yarn
      - run: lerna run build --ignore consumer
      - run: lerna run test --ignore consumer
      - run: lerna publish patch --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
