name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: pkg/webdos
          # exitOnceUploaded: true
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

  windows-test:
    # make sure the interblock library runs on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: lerna run test --scope @dreamcatcher-tech/interblock
      
  publish-npm:
    # Ensure webdos passed chromatic basic testing first
    needs: [chromatic-deployment, windows-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "interbot"
      - run: yarn
      - run: lerna run test --scope @dreamcatcher-tech/interblock
        # 👇 Ensure the package can at least build for the browser
      - run: lerna run build --scope @dreamcatcher-tech/interblock 
      - run: lerna publish patch --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
